export const ACTIVITY = {

  TASK_CREATED: "TASK_CREATED",
  TASK_ASSIGNED: "TASK_ASSIGNED",
  TASK_STARTED: "TASK_STARTED",
  TASK_SUBMITTED: "TASK_SUBMITTED",
  TASK_APPROVED: "TASK_APPROVED",

  MEMBER_ADDED: "MEMBER_ADDED",
  TL_ASSIGNED: "TL_ASSIGNED",

  WORKSHOP_CREATED: "WORKSHOP_CREATED"

};